language: c
sudo: true
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - TESTS=true
  matrix:
    - OCAML_VERSION=4.04 PACKAGE="ppx_deriving_cmdliner" TESTS=true
    - OCAML_VERSION=4.05 PACKAGE="ppx_deriving_cmdliner" TESTS=true
    - OCAML_VERSION=4.06 PACKAGE="ppx_deriving_cmdliner" TESTS=true
    - OCAML_VERSION=4.07 PACKAGE="ppx_deriving_cmdliner" TESTS=true
    - OCAML_VERSION=4.08 PACKAGE="ppx_deriving_cmdliner" TESTS=true
    - OCAML_VERSION=4.09 PACKAGE="ppx_deriving_cmdliner" TESTS=true
    - OCAML_VERSION=4.10 PACKAGE="ppx_deriving_cmdliner" TESTS=true
    - OCAML_VERSION=4.11 PACKAGE="ppx_deriving_cmdliner" TESTS=true
os:
- linux
- osx

